### ISSUE TITLE
Add functions to create an Environment or Database from raw MDB values

### ISSUE THREAD

**Issue by PlasmaPower** [AltSysrq/lmdb-zero#12]
This would be useful when interfacing with a C or C++ project. We should have an unsafe function on `Environment` to create a new environment from a `*mut MDB_env` and an unsafe function on `Database` to create a new database from an `MDB_dbi`.

These functions would be dangerous, because we couldn't infer the lifetime, but they would be useful.

**Comment by AltSysrq** [comment]
Great suggestion!

I've added methods to `Environment` and `Database` for this, available in 0.4.4. Note that you do need to create the `Environment` first and then bind the `MDB_dbi` to it, since the `MDB_dbi` is a plain integer rather than a pointer to some structure.

Feel free to reopen this issue if the new functions aren't sufficient for your use case.

**Comment by PlasmaPower** [comment]
This is perfect! Thank you very much for the quick addition.
