### ISSUE TITLE
Transaction and cursor in struct

### ISSUE THREAD

**Issue by katyo** [AltSysrq/lmdb-zero#13]
I implementing rust iterator which should use cursor for data extraction
I don't understand the proper way to do that.
I store transaction and cursor in struct which implements iterator but it causes lifetime inconsistency.
Can anybody give me short example for this case of usage?

```rust
pub struct KeyIter {
    txn: Rc<ReadTransaction<'static>>,
    cur: Rc<Cursor<'static, 'static>>,
    init: bool,
}

impl KeyIter {
    pub fn new(env: Arc<Environment>, db: Arc<Database<'static>>) -> Result<Self> {
        let txn = Rc::new(ReadTransaction::new(env.clone())?);
        let cur = Rc::new(txn.cursor(db.clone())?);
        
        Ok(Self { txn, cur, init: false })
    }
}
```

The rustc output:

```
...
258 |         let cur = Rc::new(txn.cursor(db.clone())?);
    |                           ^^^ borrowed value does not live long enough
...
273 |     }
    |     - borrowed value only lives until here
...
```

**Comment by AltSysrq** [comment]
There's an example here: https://docs.rs/lmdb-zero/0.4.4/lmdb_zero/struct.Cursor.html#example--use-reference-counting-for-more-flexibility (see the `struct Context` it defines).

In retrospect, the way this works is a bit counter-intuitive.

The first important part is to have your `Transaction` in an `Arc` or `Rc`. This will allow the cursor to hold on to it. As shown in the example, the API currently also requires the `Environment` and `Database` to similarly be in `Arc`s or `Rc`s so they have static lifetime. I'm not sure if there was a good reason for that or if it's an oversight on my part.

The other thing you need is to have the [`CreateCursor`](https://docs.rs/lmdb-zero/0.4.4/lmdb_zero/traits/trait.CreateCursor.html) trait in scope. This provides a different `cursor()` function directly on the `Arc<Transaction>` or `Rc<Transaction>`.

Finally, since this uses dynamic ownership tracking, if this is a write transaction you plan to commit, you need to manually ensure the cursor(s) are dropped, then unwrap the `Arc<Transaction>` so you can call its `commit()` method.

**Comment by katyo** [comment]
Oh, it seems I need add:

```rust
use lmdb::traits::{CreateCursor};
```

It compiled with this.

**Comment by katyo** [comment]
Thanks.
