### ISSUE TITLE
create_map<Unaligned<f64>>

### ISSUE THREAD

**Issue by katyo** [AltSysrq/lmdb-zero#14]
Is it possible to do this `DatabaseOptions::create_map::<Unaligned<f64>>()`?

I get an error:

```
error[E0277]: the trait bound `f64: lmdb::traits::LmdbRaw` is not satisfied
  --> src/index.rs:49:52
   |
49 |             (IndexKind::Unique, KeyType::Float) => DatabaseOptions::create_map::<Unaligned<f64>>(),
   |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `lmdb::traits::LmdbRaw` is not implemented for `f64`
   |
   = note: required because of the requirements on the impl of `lmdb::traits::LmdbOrdKeyIfUnaligned` for `f64`
   = note: required because of the requirements on the impl of `lmdb::traits::LmdbOrdKey` for `lmdb::Unaligned<f64>`
   = note: required by `lmdb::DatabaseOptions::create_map`
```

**Comment by AltSysrq** [comment]
The compiler's error message here is unfortunate. The actual problem is that `f64` is not `LmdbOrdKeyIfUnaligned` because `f64` is not `Ord`.

You have a couple options here.

The `u64` representation of `f64` sorts real numbers and infinities the same way and gives NaNs a consistent (but not useful) total ordering with the rest of the values, so you could use `create_map::<Unaligned<u64>>()` and use [`from_bits`](https://doc.rust-lang.org/std/primitive.f64.html#method.from_bits) and [`to_bits`](https://doc.rust-lang.org/std/primitive.f64.html#method.to_bits) to go between `u64` and `f64` in your code.

The other option is to define your own newtype around `f64` and then add the needed impls to make it work here:

```rust
#[derive(Clone, Copy, Debug)]
struct YourWrapper(f64);
impl PartialEq for YourWrapper { ... }
impl Eq for YourWrapper { }
impl PartialOrd for YourWrapper { ... }
impl Ord for YourWrapper { ... }
unsafe impl LmdbRawIfUnaligned for YourWrapper {
  fn reported_type() -> String { "YourWrapper".to_owned() }
}
unsafe impl LmdbOrdKeyIfUnaligned for YourWrapper { }
```

There are some suggestions for dealing with NaNs in [this SO question](https://stackoverflow.com/questions/28247990/how-to-do-a-binary-search-on-a-vec-of-floats). Since your `Ord` impl will be called from C code, if you plan to use the option that delegates to a derived `PartialCmp`, you'll need to use something like `.unwrap_or_else(::std::process::abort)` instead of plain `.unwrap()` since panicking across C stack frames is undefined behaviour.

**Comment by katyo** [comment]
Thanks for explanation. I understand that floating point types have only partial eq/ord implementations but compiler really confused me by this message.
