### ISSUE TITLE
Understanding cost (not really an issue)

### ISSUE THREAD

**Issue by HandleMaser** [AltSysrq/lmdb-zero#17]
Hello!

Sorry in advance, this isn't really an issue, I'd just like to know the cost of doing : 

```
fn db_create(path_db: &str) -> (lmdb::Environment, lmdb::Database) {

    let db = lmdb::Database::open(
    unsafe {

        let mut env_builder = lmdb::EnvBuilder::new().unwrap();
        env_builder.open(path_db, lmdb::open::Flags::empty(), 0o600).unwrap()
    }, None, &lmdb::DatabaseOptions::defaults())
    .unwrap();

    let env = unsafe {

        let mut env_builder = lmdb::EnvBuilder::new().unwrap();
        env_builder.open(path_db, lmdb::open::Flags::empty(), 0o600).unwrap()
    };


    return (env, db);

}
```

I have to do the Env = unsafe twice because of this error
&env, None, &lmdb::DatabaseOptions::defaults())
    |      ^^^ borrowed value does not live long enough

Question is, is it costly to do what i'm doing? Can I avoid doing the 'env' variable twice? 
My code is working, but I'm scared of having to "double up" everything

**Comment by AltSysrq** [comment]
You should be able to use `Arc` to escape the lifetime restrictions.

```rust
fn db_create(path_db: &str)
             -> (Arc<lmdb::Environment>, lmdb::Database<'static>) {
    let env = Arc::new(unsafe {
        let mut env_builder = lmdb::EnvBuilder::new().unwrap();
        env_builder.open(path_db, lmdb::open::Flags::empty(), 0o600).unwrap()
    });
    let db = lmdb::Database::open(
        Arc::clone(&env),
        None,
        &lmdb::DatabaseOptions::defaults()).unwrap();
    (env, db)
}
```

See [this section of the docs](https://docs.rs/lmdb-zero/0.4.4/lmdb_zero/struct.Database.html#shared-mode) for more detail.

Another option is to just pass the `Database` around and use `Database::env()` to get the `Environment` when you need it, if you have just one `Database`.

**Comment by HandleMaser** [comment]
Amazing! Thanks

**Comment by pakipaki2000** [comment]
PS: Is Arc slowing down the code?

**Comment by HandleMaser** [comment]
the trait bound `supercow::Supercow<'_, lmdb::Environment, lmdb::Environment, std::boxed::Box<(dyn supercow::NonSyncFeatures<'static> + 'static)>>: std::convert::From<&std::sync::Arc<lmdb::Environment>>` is not satisfied

I get this error message on:
let txn = lmdb::WriteTransaction::new(&env).unwrap();

PS: I used your code

**Comment by AltSysrq** [comment]
> Is Arc slowing down the code?

Not really. Creating and dropping a `Database` is moderately expensive (LMDB has to walk one of its btrees, and `lmdb-zero` updates a table of databes ids inside a mutex), so simply adding one atomic increment/decrement isn't going to have much effect. As for using the `Database` once it's created, there's no additional overhead with either approach.

If I had to rewrite `lmdb-zero` today, I'd probably just make this part of the API always work with `Arc`s (possibly just internally). It is like it is because it originally only took plain references (i.e. `&Environment`) and the API was later retrofitted to accept `Arc`s and owned values for better ergonomics.

**Comment by AltSysrq** [comment]
> the trait bound … is not satisfied

You need to say what you want to do with the reference here.

```rust
// Pay the (small) cost of cloning the Arc but get a
// lmdb::WriteTransaction<'static>
let mut txn = lmdb::WriteTransaction::new(Arc::clone(&env)).unwrap();
// Dereference the Arc to get a plain &Environment to avoid overhead,
// but the lifetime of txn is now bound to that of env
let mut txn = lmdb::WriteTransaction::new(&*env).unwrap();
```

**Comment by HandleMaser** [comment]
Thanks! it's working.

Should i let lmdb::WriteTransaction::new(db.env).unwrap(); opened?

let's say I do a db_write function, do I need to do that inside it or outside and only once?

**Comment by HandleMaser** [comment]
Is that correct & optimal?

```
fn db_write(db: &DBContext, key: &str, value: &str) -> bool
{
    let txn = lmdb::WriteTransaction::new(&*db.env).unwrap();
    {
        let mut access = txn.access();
        access.put(&db.wallets, key, value, lmdb::put::Flags::empty()).unwrap();
    }

    txn.commit().unwrap();
    return true;
}

```

**Comment by AltSysrq** [comment]
It really depends on exactly what you're doing. I can give a few poithers though.

- You can only have one `WriteTransaction` at a time. If you try to create a second one on the same thread, the thread will deadlock.

- It's more efficient to have one large transaction than many small ones.

- Other readers won't be able to see written changes until the `WriteTransaction` is committed, so you can't just hold on to one transaction for the whole program.

The example code you posted looks fine to me. (If that's "serious" code though I would recommend eventually making it propagate `Result`s instead of using `unwrap()` though.)

**Comment by HandleMaser** [comment]
Thanks so much! You are very helpful.

Unfortunately yeah it's for productive environement for my boss, I know I'm kinda abusing but do you mind giving me an example of the Result instead of unwrap()? I'm beginner in Rust

**Comment by AltSysrq** [comment]
Have a look at [the Rust book](https://doc.rust-lang.org/book/ch09-02-recoverable-errors-with-result.html).

For code where the only errors are from `lmdb_zero`, you can start by just using `lmdb_zero`'s error type directly. Your code above would become something like

```rust
use lmdb_zero::error::Error as LmdbError;
fn db_write(db: &DBContext, key: &str, value: &str) -> Result<bool, LmdbError>
{
    let txn = lmdb::WriteTransaction::new(&*db.env)?;
    {
        let mut access = txn.access();
        access.put(&db.tx, key, value, lmdb::put::Flags::empty())?;
    }

    txn.commit()?;
    return true;
}
```

If/when you need to handle multiple error types, there are other crates like [`failure`](https://crates.io/crates/failure) or [`error-chain`](https://crates.io/crates/error-chain) that make it easy to define your own error type with automatic conversions from the other types.

**Comment by HandleMaser** [comment]
Amazing! Helped me a lot to understand.
