### ISSUE TITLE
Fastest

### ISSUE THREAD

**Issue by pakipaki2000** [AltSysrq/lmdb-zero#18]
Hi!

Thanks for your amazing library, it's very well documented, appreciated.

I'd like to ask an advise from you.
I can see in one example that you Insert a Struct (I mean 2x i32) types directly in the Db with:
pub fn put_reserve<K: AsLmdbBytes + ?Sized, V: FromReservedLmdbBytes + Sized>(

Is it faster to insert & retrieve a Struct like you did or use a String with "/" and split the elements at retrieval?

What's your intake?
I have maybe 5-6 data to store in the value, JSON is slow... I'd like to avoid parsing as much as I can so a basic split is nice but I'm really surprised to see that in your example you insert directly your Struct.

Thank you very much!

**Comment by pakipaki2000** [comment]
Tried many different things, can't retrieve the value I've inserted in the DB later on, String is not valid UTF-8, how can I retrieve my struct as it was inserted? :)

**Comment by pakipaki2000** [comment]
access.get::<str,str> doesn't work to fetch back a u32 in my case, I must be doing something wrong

**Comment by AltSysrq** [comment]
Writing a struct directly is the fastest option as it is as fast as just initialising the struct in memory. However, it has pretty [serious ramifications](https://docs.rs/lmdb-zero/0.4.4/lmdb_zero/traits/trait.LmdbRaw.html) so I would advise against going that route unless either (a) you're comfortable with reasoning about how the compiler lays structs out in memory and are willing to bear the maintenance burden of coupling your database data to those structs, or (b) you're only using the database within the one single process that builds it.

Otherwise, my suggestion is to use [Serde](https://serde.rs/) in conjunction with one of the binary codecs — `bincode` is a good option if your database doesn't need to be read by anything but your own application, otherwise there's a number of "binary JSON" variants like CBOR or MessagePack (which I don't have substantial personal experience with). In this route, you'd be using `Serde` to turn your data into byte arrays and then using `&[u8]` values with `lmdb-zero`.

**Comment by pakipaki2000** [comment]
Thanks so much!
Problem is I have about 2-3 millions to read everything seconds, I'm scared Serde is too slow for that.

"this will almost certainly lead to undefined behaviour." in your article, do you mean the data could be incorrect?

I would use the same struct among processes.

**Comment by AltSysrq** [comment]
I assume you're talking about this paragraph:

> If the tagged type contains pointers of any kind, they will be stored in and retrieved from the database, which has serious ramifications, especially when the `FromReservedLmdbBytes` implementation is used. If the type contains Rust references, this will almost certainly lead to undefined behaviour.

If your struct contains pointers of any kind, including references, the _pointer itself_, not the _data being pointed to_, gets written. This means you could read it back in with the wrong lifetime, or after the thing it points to has been dropped. In the case of `put_reserve`, it will also make visible pointers with whatever value happened to be there before. What happens then if those pointers are anything other than raw pointers is unpredictable and entirely depends on your code and how LLVM optimises it.

I would be surprised if serde with bincode is too slow for your use case.

**Comment by pakipaki2000** [comment]
Very interesting! Your lib is quite amazing I'm impressed.

I have 1+Millions insert / second and Bincode I'm a bit scared it will put the CPU 100% for a while.
