### ISSUE TITLE
Regarding unsafety of mapsize

### ISSUE THREAD

**Issue by oersted** [AltSysrq/lmdb-zero#34]
The docs of `EnvBuilder::set_mapsize` say the following.

> The size should be a multiple of the OS page size. The default is 10485760 bytes. The size of the memory map is also the maximum size of the database. The value should be chosen as large as possible, to accommodate future growth of the database.

But then, in `EnvBuilder::open` it says this regarding unsafety.

> If the caller uses flags that result in the creation of a sparse file, the caller must ensure there is actually sufficient disk space for all pages of the file or else a segfault may occur.

This is not entirely contradictory, "as large as possible" could be interpreted to mean as much disk space as is available. But isn't the whole point of using sparse files that the DB will use only as much disk space as it needs while leaving the rest free?

One can set a mapsize that is smaller than the available disk space when creating the `Environment`. But how can a user of the library guarantee that part of that disk space will not be used by other processes later on? Of course, one could reserve the whole mapsize up-front, but this is rather impractical for most-use cases, which is precisely why sparse files are used.

The C API will return `ENOSPC` on commit if there is not enough disk space, rather than crashing. I don't see a direct equivalent among the error constants at `lmdb_zero::error`, is it `MAP_FULL`? Why do the docs say that there may be segfaults when the disk is full, rather than returning `Result::Err(Error::Code(...))` on `WriteTransaction::commit`? 

**Side question**: What happens if mapsize is not "a multiple of OS page size"? Is it a strict requirement? I know this comes from the original C library docs, but there doesn't seem to be an explanation, perhaps someone here knows.

**Comment by oersted** [comment]
Somewhat offtopic but still about safety. `EnvBuilder::open` also states:

> The caller must ensure that no other process writes to the file in any way except going through LMDB. If this is violated, segfaults can occur, or immutable references can be observed to have their referent mutated asynchronously.

But doesn't `lmdb` use `flock(2)` internally already? How is the caller supposed to lock the file before `lmdb` opens it (or creates it even)?

**Comment by AltSysrq** [comment]
> "as large as possible" could be interpreted to mean as much disk space as is available.

That sentence is from the LMDB docs. I think what they're getting at is that you can't be conservative about the initial size since you can't resize the DB while it's in use.

> The C API will return ENOSPC on commit if there is not enough disk space

This actually only happens when using a non-sparse file. LMDB doesn't make any system calls when not setting up / resizing the DB. In the case of sparse files, the OS tries to allocate pages of the file the first time LLMDB writes to them (which it does by just writing memory). But if there's no space, it can't return an error since there was no system call being made, so its only option is to signal the process with `SIGBUS`.

> But isn't the whole point of using sparse files that the DB will use only as much disk space as it needs while leaving the rest free?

Yes. If you're willing to make the sparse file tradeoffs, you might as well make the nominal size bigger than you'll ever need.

> But how can a user of the library guarantee that part of that disk space will not be used by other processes later on?

You can't. LLDB's essentially built on gaining simplicity and performance by abdicating I/O and caching to the virtual memory manager, which means it can't deal with this situation gracefully. Overall it's a similar situation to overcommit on Linux where a process can just get killed instead of receiving an allocation failure.

> What happens if mapsize is not "a multiple of OS page size"?

I would expect that the underlying allocation just gets rounded up but you can't use it. E.g. if you request 5000 bytes you'd probably get an 8192-byte file but LMDB would only know about the requested 5000 bytes.

> But doesn't `lmdb` use `flock(2)` internally already?

Yes, but `flock` only affects other processes that also `flock`. Anything that doesn't use that API can write unimpeded.

> How is the caller supposed to lock the file before `lmdb` opens it (or creates it even)?

You can't. Basically the issue is that uncontrolled writing to the file has similar implications to writing to `/proc/$pid/mem`. It's something I could have been clearer on in that part of the documentation, but basically you want to ensure that either (a) your process is in an entirely trusted environment (e.g. a container with nothing else in it) or (b) the LMDB map file is in a sufficiently safe place that the only "attack" vector is basically the user attacking themselves (akin to writing to `/proc/$pid/mem` or putting a debugger on the process).

**Comment by oersted** [comment]
Thank you so much for taking the time to write a thorough response, this is extremely helpful.

Now I understand... There's just no general and "automatic" way to enforce some of these conditions, which makes sense, you would have enforced them in your implementation otherwise. The only way to ensure safe usage of LMDB is to use it in a machine where you can know for sure that there will be no other process that will touch the file or consume the disk space it requires.

This is rather restrictive, but it is a reasonable trade-off for performance.

The condition regarding disk usage is hard to swallow. Our system needs a key-value store alongside various other systems that use disk, such as sqlite and tantivy. Besides, we need the key-value store to act as a cache, so it should have a reliable way to signal when it is full. I guess using a non-sparse file is the answer, it is somewhat wasteful but could be a decent solution.

Another option is to use another backend with broader guarantees, we are considering RocksDB, but it is rather bothersome that it doesn't allow multiple values per key like LMDB.

This is not relevant so relevant to this thread, but since you seem to be quite knowledgeable in this area, is there any alternative you would recommend? I'll close the issue in the meantime, your answer fully clarified our doubts.

**Comment by oersted** [comment]
I thought there was a flag to force the file to be non-sparse, seems I misremembered. Is there a clean way to reserve the whole mapsize when creating the Environment in Linux? Alternatively, a way to reserve the file outside of LMDB such that the space is always guaranteed to be available? Then perhaps the file can be given to LMDB with NOSUBDIR?
